## Importing the relavant libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

### Step 1 Loading the data

In [2]:
raw_data = pd.read_csv("./adult/adult.data")

raw_data.head(10)

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
5,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
6,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
7,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
8,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
9,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K

In [3]:
data = raw_data.copy()

In [4]:
# The dataset does not have the appropriate columns
# Columns from the dataset documentation
columns = [
    "age", "workclass", "fnlwgt", "education", "education-num",
    "marital-status", "occupation", "relationship", "race", "sex",
    "capital-gain", "capital-loss", "hours-per-week", "native-country", "income"
]

In [5]:
# loading the data with the appropriate columns
data = pd.read_csv(
    "./adult/adult.data", header=None, 
    names=columns, sep=r",\s*", engine="python"
    )

In [6]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [7]:
data.shape

(32561, 15)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [9]:
data.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

### Step 2 Identifing missing values

In [10]:
(data == "?").sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

In [11]:
# Dropping rows with missing values 
data = data.dropna()

### Step 3 Checking for duplicates

In [12]:
data.duplicated().sum()
data = data.drop_duplicates()

### Step 4 - Inspecting target variable

In [13]:
data["income"].value_counts()

income
<=50K    24698
>50K      7839
Name: count, dtype: int64

### Step 5 Dropping or reconsidering irrelevant/redundant features

In [14]:
data = data.drop(columns=["fnlwgt", "education"])

### Step 6 Encoding categorical variables

In [15]:
top_countries = data["native-country"].value_counts().nlargest(5).index

data["native-country"] = data["native-country"].where(data["native-country"].isin(top_countries), "Other")

In [16]:
data["income"] = data["income"].map({"<=50K": 0,">50K": 1})

categorical_cols = [
                    "workclass", "marital-status", "occupation",
                    "relationship", "race", "sex", "native-country"
                    ]
data = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

### Step 7 Checking for outliers

In [17]:
data[["age", "capital-gain", "capital-loss", "hours-per-week"]].describe()

                age  capital-gain  capital-loss  hours-per-week
count  32537.000000  32537.000000  32537.000000    32537.000000
mean      38.585549   1078.443741     87.368227       40.440329
std       13.637984   7387.957424    403.101833       12.346889
min       17.000000      0.000000      0.000000        1.000000
25%       28.000000      0.000000      0.000000       40.000000
50%       37.000000      0.000000      0.000000       40.000000
75%       48.000000      0.000000      0.000000       45.000000
max       90.000000  99999.000000   4356.000000       99.000000

In [18]:
data["capital-gain"] = np.log1p(data["capital-gain"])
data["capital-loss"] = np.log1p(data["capital-loss"])

In [19]:
data.head(20)

,age,education-num,capital-gain,capital-loss,hours-per-week,income,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Male,native-country_Germany,native-country_Mexico,native-country_Other,native-country_Philippines,native-country_United-States
0,39,13,7.684784,0.0,40,0,False,False,False,False,...,False,False,False,True,True,False,False,False,False,True
1,50,13,0.000000,0.0,13,0,False,False,False,False,...,False,False,False,True,True,False,False,False,False,True
2,38,9,0.000000,0.0,40,0,False,False,False,True,...,False,False,False,True,True,False,False,False,False,True
3,53,7,0.000000,0.0,40,0,False,False,False,True,...,False,True,False,False,True,False,False,False,False,True
4,28,13,0.000000,0.0,40,0,False,False,False,True,...,False,True,False,False,False,False,False,True,False,False
5,37,14,0.000000,0.0,40,0,False,False,False,True,...,False,False,False,True,False,False,False,False,False,True
6,49,5,0.000000,0.0,16,0,False,False,False,True,...,False,True,False,False,False,False,False,True,False,False
7,52,9,0.000000,0.0,45,1,False,False,False,False,...,False,False,False,True,True,False,False,False,False,True
8,31,14,9.552866,0.0,50,1,False,False,False,True,...,False,False,False,True,False,False,False,False,False,True
9,42,13,8.552367,0.0,40,1,False,False,False,True,...,False,False,False,True,True,False,False,False,False,True
10,37,10,0.000000,0.0,80,1,False,False,False,True,...,False,True,False,False,True,False,False,False,False,True
11,30,13,0.000000,0.0,40,1,False,False,False,False,...,True,False,False,False,True,False,False,True,False,False
12,23,13,0.000000,0.0,30,0,False,False,False,True,...,False,False,False,True,False,False,False,False,False,True
13,32,12,0.000000,0.0,50,0,False,False,False,True,...,False,True,False,False,True,False,False,False,False,True
14,40,11,0.000000,0.0,40,1,False,False,False,True,...,True,False,False,False,True,False,False,False,False,False
15,34,4,0.000000,0.0,45,0,False,False,False,True,...,False,False,False,False,True,False,True,False,False,False
16,25,9,0.000000,0.0,35,0,False,False,False,False,...,False,False,False,True,True,False,False,False,False,True
17,32,9,0.000000,0.0,40,0,False,False,False,True,...,False,False,False,True,True,False,False,False,False,True
18,38,7,0.000000,0.0,50,0,False,False,False,True,...,False,False,False,True,True,False,False,False,False,True
19,43,14,0.000000,0.0,45,1,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True

### Step 8 Splitting into train/test

In [20]:
from sklearn.model_selection import train_test_split

X = data.drop(columns=["income"])
y = data["income"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

### Step 9 Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
numeric_cols = [
    "age", "education-num", "capital-gain", 
    "capital-loss", "hours-per-week"
    ]

scaler = StandardScaler()

X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.fit_transform(X_test[numeric_cols])

### Step 10 Saving the numeric, scaled X_train and X_test data

In [ ]:
X_train.to_csv("./adult/scaled_data/X_train.csv", index=False)
X_test.to_csv("./adult/scaled_data/X_test.csv", index=False)
y_train.to_csv("./adult/scaled_data/y_train.csv", index=False)
y_test.to_csv("./adult/scaled_data/y_test.csv", index=False)

'X_train.to_csv("./adult/scaled_data/X_train.csv", index=False)\nX_test.to_csv("./adult/scaled_data/X_test.csv", index=False)\ny_train.to_csv("./adult/scaled_data/y_train.csv", index=False)\ny_test.to_csv("./adult/scaled_data/y_test.csv", index=False)'