In [10]:
import numpy as np 
import pandas as pd
from apyori import apriori

In [11]:
store_dataset = pd.read_csv('./Datasets/store_data.csv')
store_dataset.head()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
store_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   shrimp             7500 non-null   object
 1   almonds            5746 non-null   object
 2   avocado            4388 non-null   object
 3   vegetables mix     3344 non-null   object
 4   green grapes       2528 non-null   object
 5   whole weat flour   1863 non-null   object
 6   yams               1368 non-null   object
 7   cottage cheese     980 non-null    object
 8   energy drink       653 non-null    object
 9   tomato juice       394 non-null    object
 10  low fat yogurt     255 non-null    object
 11  green tea          153 non-null    object
 12  honey              86 non-null     object
 13  salad              46 non-null     object
 14  mineral water      24 non-null     object
 15  salmon             7 non-null      object
 16  antioxydant juice  3 non-null      object
 17  frozen smoothie    3 non-null      object
 18  spinach            2 non-null      object
 19  olive oil          0 non-null      float64
dtypes: float64(1), object(19)
memory usage: 1.1+ MB

In [13]:
store_dataset = pd.read_csv('./Datasets/store_data.csv', header=None)

In [14]:
store_dataset.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Converting the data frame into a list

In [15]:
all_records = []
for i in range(0, 7501):
    all_records.append([str(store_dataset.values[i, j]) for j in range(0, 20)])

In [16]:
apriori_rules = apriori(all_records, min_support=0.003, min_confidence=0.1, min_lift=2, min_length=2)
apriori_rules = list(apriori_rules)
print(len(apriori_rules))

832

In [17]:
print(apriori_rules[0])

RelationRecord(items=frozenset({'burgers', 'almonds'}), support=0.005199306759098787, ordered_statistics=[OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'burgers'}), confidence=0.25490196078431376, lift=2.923577382023146)])

In [18]:
for rule in apriori_rules:
    item_pair = rule[0]
    items = [x for x in item_pair]
    print("The apriori rule is: " + items[0] + "->" + items[1])
    
    print("The support for the rule is: " + str(rule[1]))
    print("The confidence for the rule is: " + str(rule[2][0][2]))
    print("The lift for the rule is: " + str(rule[2][0][3]))
    print("***********************")

The apriori rule is: burgers->almonds
The support for the rule is: 0.005199306759098787
The confidence for the rule is: 0.25490196078431376
The lift for the rule is: 2.923577382023146
***********************
The apriori rule is: avocado->frozen smoothie
The support for the rule is: 0.005065991201173177
The confidence for the rule is: 0.152
The lift for the rule is: 2.4003200000000002
***********************
The apriori rule is: soup->avocado
The support for the rule is: 0.004399413411545127
The confidence for the rule is: 0.132
The lift for the rule is: 2.6124854881266493
***********************
The apriori rule is: spaghetti->bacon
The support for the rule is: 0.003199573390214638
The confidence for the rule is: 0.36923076923076925
The lift for the rule is: 2.1206738131699847
***********************
The apriori rule is: black tea->milk
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.29906542056074764
The lift for the rule is: 2.3079112341833006
***********************
The apriori rule is: spaghetti->blueberries
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.37681159420289856
The lift for the rule is: 2.164214217546663
***********************
The apriori rule is: body spray->french fries
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.37209302325581395
The lift for the rule is: 2.17712150346479
***********************
The apriori rule is: brownies->cottage cheese
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.10276679841897232
The lift for the rule is: 3.225329518580382
***********************
The apriori rule is: burgers->french wine
The support for the rule is: 0.0041327822956939075
The confidence for the rule is: 0.1834319526627219
The lift for the rule is: 2.103857915784521
***********************
The apriori rule is: burgers->ham
The support for the rule is: 0.005599253432875617
The confidence for the rule is: 0.21105527638190955
The lift for the rule is: 2.420681388594348
***********************
The apriori rule is: butter->chicken
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.1415929203539823
The lift for the rule is: 2.360196656833825
***********************
The apriori rule is: fresh tuna->cake
The support for the rule is: 0.0037328356219170776
The confidence for the rule is: 0.16766467065868262
The lift for the rule is: 2.0685077213993064
***********************
The apriori rule is: herb & pepper->cereals
The support for the rule is: 0.003199573390214638
The confidence for the rule is: 0.12435233160621763
The lift for the rule is: 2.5141963325558985
***********************
The apriori rule is: milk->cereals
The support for the rule is: 0.007065724570057326
The confidence for the rule is: 0.2746113989637306
The lift for the rule is: 2.119197637476279
***********************
The apriori rule is: cooking oil->chicken
The support for the rule is: 0.006799093454206106
The confidence for the rule is: 0.11333333333333334
The lift for the rule is: 2.2196170583115755
***********************
The apriori rule is: fresh bread->chicken
The support for the rule is: 0.005199306759098787
The confidence for the rule is: 0.12074303405572756
The lift for the rule is: 2.0126522187822498
***********************
The apriori rule is: light cream->chicken
The support for the rule is: 0.004532728969470737
The confidence for the rule is: 0.29059829059829057
The lift for the rule is: 4.84395061728395
***********************
The apriori rule is: meatballs->chicken
The support for the rule is: 0.003199573390214638
The confidence for the rule is: 0.15286624203821658
The lift for the rule is: 2.548110403397028
***********************
The apriori rule is: tomato sauce->chocolate
The support for the rule is: 0.005065991201173177
The confidence for the rule is: 0.3584905660377358
The lift for the rule is: 2.1879883936932925
***********************
The apriori rule is: eggs->cider
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.4050632911392405
The lift for the rule is: 2.2539909101153137
***********************
The apriori rule is: milk->cider
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.31645569620253167
The lift for the rule is: 2.4421133510444344
***********************
The apriori rule is: cooking oil->grated cheese
The support for the rule is: 0.005732568990801226
The confidence for the rule is: 0.11227154046997388
The lift for the rule is: 2.1428723284103666
***********************
The apriori rule is: cooking oil->herb & pepper
The support for the rule is: 0.005332622317024397
The confidence for the rule is: 0.10443864229765012
The lift for the rule is: 2.111574813678365
***********************
The apriori rule is: cooking oil->soup
The support for the rule is: 0.005332622317024397
The confidence for the rule is: 0.10443864229765012
The lift for the rule is: 2.067003313653492
***********************
The apriori rule is: frozen smoothie->cottage cheese
The support for the rule is: 0.004932675643247567
The confidence for the rule is: 0.15481171548117154
The lift for the rule is: 2.4447214269984583
***********************
The apriori rule is: mushroom cream sauce->escalope
The support for the rule is: 0.005732568990801226
The confidence for the rule is: 0.3006993006993007
The lift for the rule is: 3.790832696715049
***********************
The apriori rule is: pasta->escalope
The support for the rule is: 0.005865884548726837
The confidence for the rule is: 0.3728813559322034
The lift for the rule is: 4.700811850163794
***********************
The apriori rule is: extra dark chocolate->mineral water
The support for the rule is: 0.005732568990801226
The confidence for the rule is: 0.47777777777777775
The lift for the rule is: 2.0043686303753416
***********************
The apriori rule is: green tea->flax seed
The support for the rule is: 0.0030662578322890282
The confidence for the rule is: 0.3382352941176471
The lift for the rule is: 2.560144239330445
***********************
The apriori rule is: olive oil->french wine
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.15384615384615383
The lift for the rule is: 2.336032388663967
***********************
The apriori rule is: fresh bread->tomato juice
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.14035087719298245
The lift for the rule is: 3.2593558198902826
***********************
The apriori rule is: fresh tuna->honey
The support for the rule is: 0.003999466737768298
The confidence for the rule is: 0.17964071856287428
The lift for the rule is: 3.7850703088205613
***********************
The apriori rule is: fresh tuna->olive oil
The support for the rule is: 0.0037328356219170776
The confidence for the rule is: 0.16766467065868262
The lift for the rule is: 2.5458556571068387
***********************
The apriori rule is: fresh tuna->pancakes
The support for the rule is: 0.005065991201173177
The confidence for the rule is: 0.2275449101796407
The lift for the rule is: 2.3938490480469636
***********************
The apriori rule is: honey->fromage blanc
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.2450980392156863
The lift for the rule is: 5.164270764485569
***********************
The apriori rule is: hot dogs->frozen smoothie
The support for the rule is: 0.004799360085321957
The confidence for the rule is: 0.14814814814814814
The lift for the rule is: 2.339493177387914
***********************
The apriori rule is: frozen smoothie->vegetables mix
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.1295336787564767
The lift for the rule is: 2.0455413144259618
***********************
The apriori rule is: parmesan cheese->frozen vegetables
The support for the rule is: 0.005465937874950006
The confidence for the rule is: 0.27516778523489926
The lift for the rule is: 2.886760219646125
***********************
The apriori rule is: shrimp->frozen vegetables
The support for the rule is: 0.01666444474070124
The confidence for the rule is: 0.17482517482517482
The lift for the rule is: 2.4465739484396196
***********************
The apriori rule is: frozen vegetables->tomatoes
The support for the rule is: 0.0161311825089988
The confidence for the rule is: 0.1692307692307692
The lift for the rule is: 2.4744639376218323
***********************
The apriori rule is: ground beef->grated cheese
The support for the rule is: 0.011331822423676844
The confidence for the rule is: 0.2162849872773537
The lift for the rule is: 2.201294015695292
***********************
The apriori rule is: grated cheese->herb & pepper
The support for the rule is: 0.006532462338354886
The confidence for the rule is: 0.12468193384223919
The lift for the rule is: 2.5208603389505018
***********************
The apriori rule is: grated cheese->salmon
The support for the rule is: 0.005199306759098787
The confidence for the rule is: 0.12225705329153606
The lift for the rule is: 2.333460958625476
***********************
The apriori rule is: green beans->spaghetti
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.39999999999999997
The lift for the rule is: 2.29739663093415
***********************
The apriori rule is: ground beef->herb & pepper
The support for the rule is: 0.015997866951073192
The confidence for the rule is: 0.1628222523744912
The lift for the rule is: 3.291993841134928
***********************
The apriori rule is: ground beef->light cream
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.2136752136752137
The lift for the rule is: 2.174732398612996
***********************
The apriori rule is: ground beef->olive oil
The support for the rule is: 0.014131449140114652
The confidence for the rule is: 0.14382632293080055
The lift for the rule is: 2.183889166607156
***********************
The apriori rule is: ground beef->pepper
The support for the rule is: 0.006532462338354886
The confidence for the rule is: 0.24623115577889446
The lift for the rule is: 2.5060785610549354
***********************
The apriori rule is: ground beef->rice
The support for the rule is: 0.004399413411545127
The confidence for the rule is: 0.23404255319148934
The lift for the rule is: 2.3820260400127022
***********************
The apriori rule is: ground beef->salmon
The support for the rule is: 0.008932142381015865
The confidence for the rule is: 0.21003134796238246
The lift for the rule is: 2.137646053006555
***********************
The apriori rule is: ground beef->spaghetti
The support for the rule is: 0.03919477403012932
The confidence for the rule is: 0.3989145183175034
The lift for the rule is: 2.291162176033379
***********************
The apriori rule is: ground beef->tomato sauce
The support for the rule is: 0.005332622317024397
The confidence for the rule is: 0.3773584905660377
The lift for the rule is: 3.840659481324083
***********************
The apriori rule is: olive oil->ham
The support for the rule is: 0.0035995200639914677
The confidence for the rule is: 0.13567839195979897
The lift for the rule is: 2.060169267389579
***********************
The apriori rule is: whole wheat rice->ham
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.1608040201005025
The lift for the rule is: 2.7475875962958294
***********************
The apriori rule is: herb & pepper->whole wheat pasta
The support for the rule is: 0.0037328356219170776
The confidence for the rule is: 0.12669683257918551
The lift for the rule is: 2.5615982241953383
***********************
The apriori rule is: olive oil->light cream
The support for the rule is: 0.003199573390214638
The confidence for the rule is: 0.20512820512820515
The lift for the rule is: 3.1147098515519573
***********************
The apriori rule is: pancakes->light cream
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.2222222222222222
The lift for the rule is: 2.3378525790868006
***********************
The apriori rule is: light mayo->pancakes
The support for the rule is: 0.005465937874950006
The confidence for the rule is: 0.20098039215686272
The lift for the rule is: 2.1143813766740918
***********************
The apriori rule is: milk->meatballs
The support for the rule is: 0.005465937874950006
The confidence for the rule is: 0.2611464968152866
The lift for the rule is: 2.0152879347854578
***********************
The apriori rule is: meatballs->tomatoes
The support for the rule is: 0.0038661511798426876
The confidence for the rule is: 0.18471337579617836
The lift for the rule is: 2.700848015296557
***********************
The apriori rule is: milk->soup
The support for the rule is: 0.015197973603519531
The confidence for the rule is: 0.11728395061728396
The lift for the rule is: 2.321231961953158
***********************
The apriori rule is: milk->whole wheat pasta
The support for the rule is: 0.009865351286495135
The confidence for the rule is: 0.33484162895927605
The lift for the rule is: 2.5839990317114503
***********************
The apriori rule is: nonfat milk->mineral water
The support for the rule is: 0.005065991201173177
The confidence for the rule is: 0.4871794871794871
The lift for the rule is: 2.0438105891126024
***********************
The apriori rule is: shrimp->oil
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.15028901734104047
The lift for the rule is: 2.103205072901389
***********************
The apriori rule is: salmon->olive oil
The support for the rule is: 0.005732568990801226
The confidence for the rule is: 0.1347962382445141
The lift for the rule is: 2.0467744596601216
***********************
The apriori rule is: soup->olive oil
The support for the rule is: 0.008932142381015865
The confidence for the rule is: 0.13562753036437247
The lift for the rule is: 2.684279961116512
***********************
The apriori rule is: olive oil->whole wheat pasta
The support for the rule is: 0.007998933475536596
The confidence for the rule is: 0.12145748987854252
The lift for the rule is: 4.1224100976422955
***********************
The apriori rule is: parmesan cheese->shrimp
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.16778523489932887
The lift for the rule is: 2.3480541921266154
***********************
The apriori rule is: parmesan cheese->tomatoes
The support for the rule is: 0.003199573390214638
The confidence for the rule is: 0.1610738255033557
The lift for the rule is: 2.3551944738804504
***********************
The apriori rule is: pasta->shrimp
The support for the rule is: 0.005065991201173177
The confidence for the rule is: 0.3220338983050847
The lift for the rule is: 4.506672147735896
***********************
The apriori rule is: spaghetti->pepper
The support for the rule is: 0.009865351286495135
The confidence for the rule is: 0.37185929648241206
The lift for the rule is: 2.1357707373005916
***********************
The apriori rule is: turkey->pepper
The support for the rule is: 0.0038661511798426876
The confidence for the rule is: 0.1457286432160804
The lift for the rule is: 2.3307261252959894
***********************
The apriori rule is: red wine->spaghetti
The support for the rule is: 0.010265297960271964
The confidence for the rule is: 0.36492890995260663
The lift for the rule is: 2.095966120638976
***********************
The apriori rule is: shrimp->tomatoes
The support for the rule is: 0.011198506865751233
The confidence for the rule is: 0.15671641791044774
The lift for the rule is: 2.2914811905385353
***********************
The apriori rule is: soup->tomatoes
The support for the rule is: 0.006932409012131715
The confidence for the rule is: 0.13720316622691292
The lift for the rule is: 2.0061616956492667
***********************
The apriori rule is: strong cheese->spaghetti
The support for the rule is: 0.0037328356219170776
The confidence for the rule is: 0.4827586206896552
The lift for the rule is: 2.7727200718170777
***********************
The apriori rule is: tomato sauce->spaghetti
The support for the rule is: 0.006265831222503666
The confidence for the rule is: 0.4433962264150943
The lift for the rule is: 2.546642491837383
***********************
The apriori rule is: burgers->almonds
The support for the rule is: 0.005199306759098787
The confidence for the rule is: 0.25490196078431376
The lift for the rule is: 2.923577382023146
***********************
The apriori rule is: avocado->frozen smoothie
The support for the rule is: 0.004932675643247567
The confidence for the rule is: 0.148
The lift for the rule is: 2.3420843881856537
***********************
The apriori rule is: milk->avocado
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.1
The lift for the rule is: 2.0836111111111113
***********************
The apriori rule is: milk->avocado
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.1
The lift for the rule is: 2.819924812030075
***********************
The apriori rule is: soup->avocado
The support for the rule is: 0.004399413411545127
The confidence for the rule is: 0.132
The lift for the rule is: 2.6124854881266493
***********************
The apriori rule is: spaghetti->bacon
The support for the rule is: 0.003199573390214638
The confidence for the rule is: 0.36923076923076925
The lift for the rule is: 2.1206738131699847
***********************
The apriori rule is: black tea->milk
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.29906542056074764
The lift for the rule is: 2.3079112341833006
***********************
The apriori rule is: spaghetti->blueberries
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.37681159420289856
The lift for the rule is: 2.164214217546663
***********************
The apriori rule is: body spray->french fries
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.37209302325581395
The lift for the rule is: 2.17712150346479
***********************
The apriori rule is: brownies->nan
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.10276679841897232
The lift for the rule is: 3.2388813232802995
***********************
The apriori rule is: brownies->eggs
The support for the rule is: 0.0035995200639914677
The confidence for the rule is: 0.10671936758893279
The lift for the rule is: 2.0955549117397507
***********************
The apriori rule is: burgers->chocolate
The support for the rule is: 0.0030662578322890282
The confidence for the rule is: 0.17968750000000003
The lift for the rule is: 2.216835423519737
***********************
The apriori rule is: eggs->burgers
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.18181818181818182
The lift for the rule is: 2.0853489018626634
***********************
The apriori rule is: burgers->milk
The support for the rule is: 0.0037328356219170776
The confidence for the rule is: 0.32558139534883723
The lift for the rule is: 2.5125370848885065
***********************
The apriori rule is: burgers->mineral water
The support for the rule is: 0.004799360085321957
The confidence for the rule is: 0.19672131147540983
The lift for the rule is: 2.426984469370147
***********************
The apriori rule is: burgers->frozen vegetables
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.19531250000000003
The lift for the rule is: 2.049005681818182
***********************
The apriori rule is: burgers->milk
The support for the rule is: 0.005465937874950006
The confidence for the rule is: 0.3203125
The lift for the rule is: 2.4718766075102883
***********************
The apriori rule is: burgers->shrimp
The support for the rule is: 0.0030662578322890282

## ECLAT Algorithm Implementation

In [19]:
import numpy as np
import pandas as pd 
from pyECLAT import ECLAT

data_frame = pd.read_csv("Datasets/data_market_basket.csv", header=None)

In [20]:
data_frame.head()

          0         1        2        3         4         5         6
0  corned_b   peppers  bourbon  cracker   chicken    apples      coke
1    olives   bourbon     coke   turkey  ice_crea       ham  baguette
2    hering  corned_b   olives      ham    turkey   bourbon   peppers
3  baguette  sardines   apples  peppers   avocado  ice_crea   bourbon
4  baguette      soda   hering  cracker  heineken   peppers    apples

In [21]:
eclat = ECLAT(data=data_frame)

In [22]:
get_eclat_indexes, get_ECLAT_supports = eclat.fit(
    min_support=0.02,
    min_combination=3,
    separator=' & '
)

Combination 3 by 3

1140it [00:17, 65.60it/s]

In [23]:
get_ECLAT_supports

{'baguette & cracker & ice_crea': 0.02097902097902098,
 'baguette & cracker & olives': 0.03896103896103896,
 'baguette & cracker & sardines': 0.03496503496503497,
 'baguette & cracker & avocado': 0.05094905094905095,
 'baguette & cracker & chicken': 0.03896103896103896,
 'baguette & cracker & heineken': 0.14485514485514486,
 'baguette & cracker & corned_b': 0.03796203796203796,
 'baguette & cracker & artichok': 0.03396603396603397,
 'baguette & cracker & apples': 0.03296703296703297,
 'baguette & cracker & soda': 0.12687312687312688,
 'baguette & cracker & steak': 0.023976023976023976,
 'baguette & cracker & bourbon': 0.04695304695304695,
 'baguette & cracker & hering': 0.12787212787212787,
 'baguette & cracker & peppers': 0.05094905094905095,
 'baguette & ice_crea & coke': 0.03796203796203796,
 'baguette & ice_crea & olives': 0.024975024975024976,
 'baguette & ice_crea & sardines': 0.03196803196803197,
 'baguette & ice_crea & avocado': 0.023976023976023976,
 'baguette & ice_crea & heineken': 0.04295704295704296,
 'baguette & ice_crea & apples': 0.02197802197802198,
 'baguette & ice_crea & bourbon': 0.02197802197802198,
 'baguette & ice_crea & hering': 0.025974025974025976,
 'baguette & coke & sardines': 0.029970029970029972,
 'baguette & coke & avocado': 0.023976023976023976,
 'baguette & coke & heineken': 0.03896103896103896,
 'baguette & coke & bourbon': 0.02097902097902098,
 'baguette & olives & ham': 0.02197802197802198,
 'baguette & olives & avocado': 0.028971028971028972,
 'baguette & olives & heineken': 0.04795204795204795,
 'baguette & olives & turkey': 0.03496503496503497,
 'baguette & olives & corned_b': 0.03496503496503497,
 'baguette & olives & apples': 0.03496503496503497,
 'baguette & olives & soda': 0.03596403596403597,
 'baguette & olives & bourbon': 0.03496503496503497,
 'baguette & olives & hering': 0.057942057942057944,
 'baguette & sardines & avocado': 0.1008991008991009,
 'baguette & sardines & chicken': 0.023976023976023976,
 'baguette & sardines & heineken': 0.053946053946053944,
 'baguette & sardines & artichok': 0.024975024975024976,
 'baguette & sardines & apples': 0.09490509490509491,
 'baguette & sardines & soda': 0.029970029970029972,
 'baguette & sardines & hering': 0.03496503496503497,
 'baguette & sardines & peppers': 0.09290709290709291,
 'baguette & ham & avocado': 0.023976023976023976,
 'baguette & ham & heineken': 0.029970029970029972,
 'baguette & ham & corned_b': 0.025974025974025976,
 'baguette & ham & hering': 0.04195804195804196,
 'baguette & avocado & chicken': 0.027972027972027972,
 'baguette & avocado & heineken': 0.13486513486513488,
 'baguette & avocado & turkey': 0.025974025974025976,
 'baguette & avocado & corned_b': 0.03396603396603397,
 'baguette & avocado & artichok': 0.11188811188811189,
 'baguette & avocado & apples': 0.11188811188811189,
 'baguette & avocado & soda': 0.04495504495504495,
 'baguette & avocado & steak': 0.03196803196803197,
 'baguette & avocado & bourbon': 0.03396603396603397,
 'baguette & avocado & hering': 0.12787212787212787,
 'baguette & avocado & peppers': 0.1018981018981019,
 'baguette & chicken & heineken': 0.054945054945054944,
 'baguette & chicken & artichok': 0.024975024975024976,
 'baguette & chicken & soda': 0.023976023976023976,
 'baguette & chicken & bourbon': 0.022977022977022976,
 'baguette & chicken & hering': 0.03896103896103896,
 'baguette & chicken & peppers': 0.026973026973026972,
 'baguette & heineken & turkey': 0.029970029970029972,
 'baguette & heineken & corned_b': 0.03996003996003996,
 'baguette & heineken & artichok': 0.12287712287712288,
 'baguette & heineken & apples': 0.04895104895104895,
 'baguette & heineken & soda': 0.13786213786213786,
 'baguette & heineken & steak': 0.03296703296703297,
 'baguette & heineken & bourbon': 0.04895104895104895,
 'baguette & heineken & hering': 0.2137862137862138,
 'baguette & heineken & peppers': 0.04495504495504495,
 'baguette & turkey & bourbon': 0.02097902097902098,
 'baguette & turkey & hering': 0.04095904095904096,
 'baguette & corned_b & artichok': 0.022977022977022976,
 'baguette & corned_b & apples': 0.03296703296703297,
 'baguette & corned_b & soda': 0.02097902097902098,
 'baguette & corned_b & steak': 0.02197802197802198,
 'baguette & corned_b & bourbon': 0.022977022977022976,
 'baguette & corned_b & hering': 0.060939060939060936,
 'baguette & corned_b & peppers': 0.03196803196803197,
 'baguette & artichok & apples': 0.03296703296703297,
 'baguette & artichok & soda': 0.029970029970029972,
 'baguette & artichok & hering': 0.11588411588411589,
 'baguette & artichok & peppers': 0.02097902097902098,
 'baguette & apples & soda': 0.028971028971028972,
 'baguette & apples & steak': 0.029970029970029972,
 'baguette & apples & bourbon': 0.024975024975024976,
 'baguette & apples & hering': 0.057942057942057944,
 'baguette & apples & peppers': 0.0969030969030969,
 'baguette & soda & bourbon': 0.027972027972027972,
 'baguette & soda & hering': 0.12887112887112886,
 'baguette & soda & peppers': 0.03396603396603397,
 'baguette & steak & hering': 0.04295704295704296,
 'baguette & steak & peppers': 0.02197802197802198,
 'baguette & bourbon & hering': 0.03496503496503497,
 'baguette & bourbon & peppers': 0.03896103896103896,
 'baguette & hering & peppers': 0.03996003996003996,
 'cracker & ice_crea & coke': 0.03496503496503497,
 'cracker & ice_crea & olives': 0.030969030969030968,
 'cracker & ice_crea & chicken': 0.03296703296703297,
 'cracker & ice_crea & heineken': 0.059940059940059943,
 'cracker & ice_crea & soda': 0.026973026973026972,
 'cracker & ice_crea & bourbon': 0.03996003996003996,
 'cracker & coke & olives': 0.030969030969030968,
 'cracker & coke & chicken': 0.028971028971028972,
 'cracker & coke & heineken': 0.04895104895104895,
 'cracker & coke & soda': 0.024975024975024976,
 'cracker & coke & bourbon': 0.03496503496503497,
 'cracker & olives & ham': 0.03696303696303696,
 'cracker & olives & avocado': 0.029970029970029972,
 'cracker & olives & chicken': 0.03496503496503497,
 'cracker & olives & heineken': 0.13986013986013987,
 'cracker & olives & turkey': 0.04295704295704296,
 'cracker & olives & corned_b': 0.05194805194805195,
 'cracker & olives & artichok': 0.03196803196803197,
 'cracker & olives & apples': 0.029970029970029972,
 'cracker & olives & soda': 0.1258741258741259,
 'cracker & olives & steak': 0.03196803196803197,
 'cracker & olives & bourbon': 0.13086913086913088,
 'cracker & olives & hering': 0.06793206793206794,
 'cracker & olives & peppers': 0.03196803196803197,
 'cracker & sardines & avocado': 0.03396603396603397,
 'cracker & sardines & chicken': 0.023976023976023976,
 'cracker & sardines & heineken': 0.058941058941058944,
 'cracker & sardines & apples': 0.022977022977022976,
 'cracker & sardines & soda': 0.026973026973026972,
 'cracker & sardines & hering': 0.023976023976023976,
 'cracker & sardines & peppers': 0.027972027972027972,
 'cracker & ham & avocado': 0.1048951048951049,
 'cracker & ham & chicken': 0.030969030969030968,
 'cracker & ham & heineken': 0.1258741258741259,
 'cracker & ham & turkey': 0.026973026973026972,
 'cracker & ham & corned_b': 0.05194805194805195,
 'cracker & ham & artichok': 0.1008991008991009,
 'cracker & ham & soda': 0.03896103896103896,
 'cracker & ham & bourbon': 0.03896103896103896,
 'cracker & ham & hering': 0.04095904095904096,
 'cracker & ham & peppers': 0.030969030969030968,
 'cracker & avocado & chicken': 0.023976023976023976,
 'cracker & avocado & heineken': 0.14285714285714285,
 'cracker & avocado & corned_b': 0.029970029970029972,
 'cracker & avocado & artichok': 0.11288711288711288,
 'cracker & avocado & apples': 0.026973026973026972,
 'cracker & avocado & soda': 0.04695304695304695,
 'cracker & avocado & steak': 0.02097902097902098,
 'cracker & avocado & bourbon': 0.028971028971028972,
 'cracker & avocado & hering': 0.04995004995004995,
 'cracker & avocado & peppers': 0.03496503496503497,
 'cracker & chicken & heineken': 0.08591408591408592,
 'cracker & chicken & corned_b': 0.1008991008991009,
 'cracker & chicken & artichok': 0.029970029970029972,
 'cracker & chicken & apples': 0.028971028971028972,
 'cracker & chicken & soda': 0.052947052947052944,
 'cracker & chicken & steak': 0.02197802197802198,
 'cracker & chicken & bourbon': 0.11288711288711288,
 'cracker & chicken & hering': 0.03996003996003996,
 'cracker & chicken & peppers': 0.0989010989010989,
 'cracker & heineken & turkey': 0.03996003996003996,
 'cracker & heineken & corned_b': 0.06993006993006994,
 'cracker & heineken & artichok': 0.14385614385614387,
 'cracker & heineken & bordeaux': 0.024975024975024976,
 'cracker & heineken & apples': 0.04995004995004995,
 'cracker & heineken & soda': 0.23376623376623376,
 'cracker & heineken & steak': 0.05194805194805195,
 'cracker & heineken & bourbon': 0.15084915084915085,
 'cracker & heineken & hering': 0.16283716283716285,
 'cracker & heineken & peppers': 0.06993006993006994,
 'cracker & turkey & corned_b': 0.028971028971028972,
 'cracker & turkey & soda': 0.024975024975024976,
 'cracker & turkey & bourbon': 0.03696303696303696,
 'cracker & turkey & hering': 0.03296703296703297,
 'cracker & corned_b & artichok': 0.03596403596403597,
 'cracker & corned_b & apples': 0.03396603396603397,
 'cracker & corned_b & soda': 0.04695304695304695,
 'cracker & corned_b & steak': 0.028971028971028972,
 'cracker & corned_b & bourbon': 0.11188811188811189,
 'cracker & corned_b & hering': 0.056943056943056944,
 'cracker & corned_b & peppers': 0.1018981018981019,
 'cracker & artichok & soda': 0.04795204795204795,
 'cracker & artichok & bourbon': 0.04095904095904096,
 'cracker & artichok & hering': 0.04595404595404595,
 'cracker & artichok & peppers': 0.029970029970029972,
 'cracker & apples & soda': 0.030969030969030968,
 'cracker & apples & bourbon': 0.03896103896103896,
 'cracker & apples & hering': 0.027972027972027972,
 'cracker & apples & peppers': 0.03896103896103896,
 'cracker & soda & steak': 0.03896103896103896,
 'cracker & soda & bourbon': 0.13586413586413587,
 'cracker & soda & hering': 0.14085914085914086,
 'cracker & soda & peppers': 0.052947052947052944,
 'cracker & steak & bourbon': 0.03396603396603397,
 'cracker & steak & hering': 0.03596403596403597,
 'cracker & bourbon & hering': 0.052947052947052944,
 'cracker & bourbon & peppers': 0.11688311688311688,
 'cracker & hering & peppers': 0.03796203796203796,
 'ice_crea & coke & olives': 0.11388611388611389,
 'ice_crea & coke & sardines': 0.13186813186813187,
 'ice_crea & coke & ham': 0.03996003996003996,
 'ice_crea & coke & chicken': 0.12287712287712288,
 'ice_crea & coke & heineken': 0.13886113886113885,
 'ice_crea & coke & turkey': 0.10589410589410589,
 'ice_crea & coke & corned_b': 0.026973026973026972,
 'ice_crea & coke & artichok': 0.03496503496503497,
 'ice_crea & coke & apples': 0.03696303696303696,
 'ice_crea & coke & soda': 0.026973026973026972,
 'ice_crea & coke & steak': 0.025974025974025976,
 'ice_crea & coke & bourbon': 0.11688311688311688,
 'ice_crea & coke & hering': 0.026973026973026972,
 'ice_crea & coke & peppers': 0.030969030969030968,
 'ice_crea & olives & sardines': 0.03596403596403597,
 'ice_crea & olives & ham': 0.03396603396603397,
 'ice_crea & olives & chicken': 0.027972027972027972,
 'ice_crea & olives & heineken': 0.04795204795204795,
 'ice_crea & olives & turkey': 0.1108891108891109,
 'ice_crea & olives & corned_b': 0.03896103896103896,
 'ice_crea & olives & apples': 0.03496503496503497,
 'ice_crea & olives & soda': 0.027972027972027972,
 'ice_crea & olives & steak': 0.030969030969030968,
 'ice_crea & olives & bourbon': 0.10789210789210789,
 'ice_crea & olives & hering': 0.03696303696303696,
 'ice_crea & olives & peppers': 0.022977022977022976,
 'ice_crea & sardines & ham': 0.023976023976023976,
 'ice_crea & sardines & avocado': 0.028971028971028972,
 'ice_crea & sardines & chicken': 0.11588411588411589,
 'ice_crea & sardines & heineken': 0.12287712287712288,
 'ice_crea & sardines & turkey': 0.026973026973026972,
 'ice_crea & sardines & artichok': 0.02197802197802198,
 'ice_crea & sardines & apples': 0.03496503496503497,
 'ice_crea & sardines & bourbon': 0.03896103896103896,
 'ice_crea & sardines & peppers': 0.030969030969030968,
 'ice_crea & ham & avocado': 0.02197802197802198,
 'ice_crea & ham & chicken': 0.02097902097902098,
 'ice_crea & ham & heineken': 0.03996003996003996,
 'ice_crea & ham & turkey': 0.03396603396603397,
 'ice_crea & ham & artichok': 0.025974025974025976,
 'ice_crea & ham & bourbon': 0.02197802197802198,
 'ice_crea & avocado & heineken': 0.03696303696303696,
 'ice_crea & avocado & artichok': 0.024975024975024976,
 'ice_crea & chicken & heineken': 0.11888111888111888,
 'ice_crea & chicken & corned_b': 0.030969030969030968,
 'ice_crea & chicken & bourbon': 0.04195804195804196,
 'ice_crea & chicken & peppers': 0.028971028971028972,
 'ice_crea & heineken & turkey': 0.030969030969030968,
 'ice_crea & heineken & artichok': 0.04495504495504495,
 'ice_crea & heineken & apples': 0.024975024975024976,
 'ice_crea & heineken & soda': 0.03796203796203796,
 'ice_crea & heineken & bourbon': 0.052947052947052944,
 'ice_crea & heineken & hering': 0.03896103896103896,
 'ice_crea & turkey & corned_b': 0.025974025974025976,
 'ice_crea & turkey & apples': 0.022977022977022976,
 'ice_crea & turkey & bourbon': 0.0989010989010989,
 'ice_crea & turkey & hering': 0.023976023976023976,
 'ice_crea & corned_b & bourbon': 0.022977022977022976,
 'ice_crea & corned_b & hering': 0.029970029970029972,
 'ice_crea & apples & bourbon': 0.02097902097902098,
 'ice_crea & soda & bourbon': 0.027972027972027972,
 'ice_crea & bourbon & peppers': 0.03296703296703297,
 'coke & olives & sardines': 0.03296703296703297,
 'coke & olives & ham': 0.03196803196803197,
 'coke & olives & chicken': 0.027972027972027972,
 'coke & olives & heineken': 0.04895104895104895,
 'coke & olives & turkey': 0.1048951048951049,
 'coke & olives & corned_b': 0.03596403596403597,
 'coke & olives & apples': 0.03496503496503497,
 'coke & olives & soda': 0.028971028971028972,
 'coke & olives & steak': 0.028971028971028972,
 'coke & olives & bourbon': 0.1088911088911089,
 'coke & olives & hering': 0.03596403596403597,
 'coke & sardines & ham': 0.023976023976023976,
 'coke & sardines & avocado': 0.025974025974025976,
 'coke & sardines & chicken': 0.11688311688311688,
 'coke & sardines & heineken': 0.11988011988011989,
 'coke & sardines & turkey': 0.025974025974025976,
 'coke & sardines & corned_b': 0.02097902097902098,
 'coke & sardines & apples': 0.03296703296703297,
 'coke & sardines & bourbon': 0.03796203796203796,
 'coke & sardines & peppers': 0.029970029970029972,
 'coke & ham & chicken': 0.02197802197802198,
 'coke & ham & heineken': 0.03396603396603397,
 'coke & ham & turkey': 0.028971028971028972,
 'coke & avocado & heineken': 0.028971028971028972,
 'coke & chicken & heineken': 0.11788211788211789,
 'coke & chicken & turkey': 0.02097902097902098,
 'coke & chicken & corned_b': 0.029970029970029972,
 'coke & chicken & artichok': 0.02097902097902098,
 'coke & chicken & apples': 0.02197802197802198,
 'coke & chicken & bourbon': 0.03996003996003996,
 'coke & chicken & hering': 0.02197802197802198,
 'coke & chicken & peppers': 0.027972027972027972,
 'coke & heineken & turkey': 0.030969030969030968,
 'coke & heineken & artichok': 0.03896103896103896,
 'coke & heineken & apples': 0.022977022977022976,
 'coke & heineken & soda': 0.03496503496503497,
 'coke & heineken & bourbon': 0.04995004995004995,
 'coke & heineken & hering': 0.03796203796203796,
 'coke & turkey & corned_b': 0.02097902097902098,
 'coke & turkey & apples': 0.02197802197802198,
 'coke & turkey & bourbon': 0.0979020979020979,
 'coke & turkey & hering': 0.02097902097902098,
 'coke & corned_b & apples': 0.024975024975024976,
 'coke & corned_b & bourbon': 0.022977022977022976,
 'coke & corned_b & hering': 0.027972027972027972,
 'coke & apples & bourbon': 0.022977022977022976,
 'coke & soda & bourbon': 0.026973026973026972,
 'coke & bourbon & peppers': 0.028971028971028972,
 'olives & sardines & chicken': 0.02197802197802198,
 'olives & sardines & heineken': 0.030969030969030968,
 'olives & sardines & turkey': 0.025974025974025976,
 'olives & sardines & corned_b': 0.027972027972027972,
 'olives & sardines & apples': 0.027972027972027972,
 'olives & sardines & bourbon': 0.028971028971028972,
 'olives & sardines & hering': 0.023976023976023976,
 'olives & ham & avocado': 0.028971028971028972,
 'olives & ham & heineken': 0.04095904095904096,
 'olives & ham & turkey': 0.12087912087912088,
 'olives & ham & corned_b': 0.12287712287712288,
 'olives & ham & artichok': 0.027972027972027972,
 'olives & ham & apples': 0.03196803196803197,
 'olives & ham & soda': 0.024975024975024976,
 'olives & ham & steak': 0.03396603396603397,
 'olives & ham & bourbon': 0.04895104895104895,
 'olives & ham & hering': 0.12087912087912088,
 'olives & avocado & heineken': 0.03796203796203796,
 'olives & avocado & turkey': 0.022977022977022976,
 'olives & avocado & corned_b': 0.03496503496503497,
 'olives & avocado & artichok': 0.026973026973026972,
 'olives & avocado & apples': 0.030969030969030968,
 'olives & avocado & hering': 0.04495504495504495,
 'olives & chicken & heineken': 0.03896103896103896,
 'olives & chicken & turkey': 0.02097902097902098,
 'olives & chicken & corned_b': 0.03796203796203796,
 'olives & chicken & soda': 0.023976023976023976,
 'olives & chicken & bourbon': 0.03896103896103896,
 'olives & chicken & hering': 0.030969030969030968,
 'olives & heineken & turkey': 0.04495504495504495,
 'olives & heineken & corned_b': 0.04595404595404595,
 'olives & heineken & artichok': 0.03896103896103896,
 'olives & heineken & apples': 0.029970029970029972,
 'olives & heineken & soda': 0.12687312687312688,
 'olives & heineken & steak': 0.03496503496503497,
 'olives & heineken & bourbon': 0.13286713286713286,
 'olives & heineken & hering': 0.07892107892107893,
 'olives & heineken & peppers': 0.02197802197802198,
 'olives & turkey & corned_b': 0.12187812187812187,
 'olives & turkey & artichok': 0.025974025974025976,
 'olives & turkey & apples': 0.04295704295704296,
 'olives & turkey & soda': 0.03896103896103896,
 'olives & turkey & steak': 0.04095904095904096,
 'olives & turkey & bourbon': 0.12687312687312688,
 'olives & turkey & hering': 0.12187812187812187,
 'olives & turkey & peppers': 0.030969030969030968,
 'olives & corned_b & artichok': 0.029970029970029972,
 'olives & corned_b & apples': 0.11588411588411589,
 'olives & corned_b & soda': 0.04195804195804196,
 'olives & corned_b & steak': 0.1108891108891109,
 'olives & corned_b & bourbon': 0.061938061938061936,
 'olives & corned_b & hering': 0.2017982017982018,
 'olives & corned_b & peppers': 0.03796203796203796,
 'olives & artichok & apples': 0.02097902097902098,
 'olives & artichok & bourbon': 0.03196803196803197,
 'olives & artichok & hering': 0.03896103896103896,
 'olives & apples & soda': 0.03196803196803197,
 'olives & apples & steak': 0.0989010989010989,
 'olives & apples & bourbon': 0.04595404595404595,
 'olives & apples & hering': 0.11388611388611389,
 'olives & apples & peppers': 0.029970029970029972,
 'olives & soda & steak': 0.029970029970029972,
 'olives & soda & bourbon': 0.12387612387612387,
 'olives & soda & hering': 0.06493506493506493,
 'olives & soda & peppers': 0.023976023976023976,
 'olives & steak & bourbon': 0.04395604395604396,
 'olives & steak & hering': 0.11588411588411589,
 'olives & bourbon & hering': 0.06293706293706294,
 'olives & bourbon & peppers': 0.04595404595404595,
 'olives & hering & peppers': 0.028971028971028972,
 'sardines & ham & avocado': 0.02097902097902098,
 'sardines & ham & chicken': 0.02197802197802198,
 'sardines & ham & heineken': 0.03796203796203796,
 'sardines & avocado & heineken': 0.04595404595404595,
 'sardines & avocado & artichok': 0.03196803196803197,
 'sardines & avocado & apples': 0.0919080919080919,