## Apriori Algorithm

In [1]:
import numpy as np 
import pandas as pd
from apyori import apriori

In [2]:
store_dataset = pd.read_csv('./Datasets/store_data.csv')
store_dataset.head()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
store_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   shrimp             7500 non-null   object
 1   almonds            5746 non-null   object
 2   avocado            4388 non-null   object
 3   vegetables mix     3344 non-null   object
 4   green grapes       2528 non-null   object
 5   whole weat flour   1863 non-null   object
 6   yams               1368 non-null   object
 7   cottage cheese     980 non-null    object
 8   energy drink       653 non-null    object
 9   tomato juice       394 non-null    object
 10  low fat yogurt     255 non-null    object
 11  green tea          153 non-null    object
 12  honey              86 non-null     object
 13  salad              46 non-null     object
 14  mineral water      24 non-null     object
 15  salmon             7 non-null      object
 16  antioxydant juice  3 non-null      object
 17  frozen smoothie    3 non-null      object
 18  spinach            2 non-null      object
 19  olive oil          0 non-null      float64
dtypes: float64(1), object(19)
memory usage: 1.1+ MB

In [4]:
store_dataset = pd.read_csv('./Datasets/store_data.csv', header=None)

In [5]:
store_dataset.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Converting the data frame into a list

In [6]:
all_records = []
for i in range(0, 7501):
    all_records.append([str(store_dataset.values[i, j]) for j in range(0, 20)])

In [7]:
apriori_rules = apriori(all_records, min_support=0.003, min_confidence=0.1, min_lift=2, min_length=2)
apriori_rules = list(apriori_rules)
print(len(apriori_rules))

832

In [8]:
print(apriori_rules[0])

RelationRecord(items=frozenset({'almonds', 'burgers'}), support=0.005199306759098787, ordered_statistics=[OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'burgers'}), confidence=0.25490196078431376, lift=2.923577382023146)])

In [9]:
for rule in apriori_rules:
    item_pair = rule[0]
    items = [x for x in item_pair]
    print("The apriori rule is: " + items[0] + "->" + items[1])
    
    print("The support for the rule is: " + str(rule[1]))
    print("The confidence for the rule is: " + str(rule[2][0][2]))
    print("The lift for the rule is: " + str(rule[2][0][3]))
    print("***********************")

The apriori rule is: almonds->burgers
The support for the rule is: 0.005199306759098787
The confidence for the rule is: 0.25490196078431376
The lift for the rule is: 2.923577382023146
***********************
The apriori rule is: frozen smoothie->avocado
The support for the rule is: 0.005065991201173177
The confidence for the rule is: 0.152
The lift for the rule is: 2.4003200000000002
***********************
The apriori rule is: soup->avocado
The support for the rule is: 0.004399413411545127
The confidence for the rule is: 0.132
The lift for the rule is: 2.6124854881266493
***********************
The apriori rule is: bacon->spaghetti
The support for the rule is: 0.003199573390214638
The confidence for the rule is: 0.36923076923076925
The lift for the rule is: 2.1206738131699847
***********************
The apriori rule is: black tea->milk
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.29906542056074764
The lift for the rule is: 2.3079112341833006
***********************
The apriori rule is: blueberries->spaghetti
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.37681159420289856
The lift for the rule is: 2.164214217546663
***********************
The apriori rule is: body spray->french fries
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.37209302325581395
The lift for the rule is: 2.17712150346479
***********************
The apriori rule is: cottage cheese->brownies
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.10276679841897232
The lift for the rule is: 3.225329518580382
***********************
The apriori rule is: burgers->french wine
The support for the rule is: 0.0041327822956939075
The confidence for the rule is: 0.1834319526627219
The lift for the rule is: 2.103857915784521
***********************
The apriori rule is: ham->burgers
The support for the rule is: 0.005599253432875617
The confidence for the rule is: 0.21105527638190955
The lift for the rule is: 2.420681388594348
***********************
The apriori rule is: butter->chicken
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.1415929203539823
The lift for the rule is: 2.360196656833825
***********************
The apriori rule is: cake->fresh tuna
The support for the rule is: 0.0037328356219170776
The confidence for the rule is: 0.16766467065868262
The lift for the rule is: 2.0685077213993064
***********************
The apriori rule is: herb & pepper->cereals
The support for the rule is: 0.003199573390214638
The confidence for the rule is: 0.12435233160621763
The lift for the rule is: 2.5141963325558985
***********************
The apriori rule is: cereals->milk
The support for the rule is: 0.007065724570057326
The confidence for the rule is: 0.2746113989637306
The lift for the rule is: 2.119197637476279
***********************
The apriori rule is: cooking oil->chicken
The support for the rule is: 0.006799093454206106
The confidence for the rule is: 0.11333333333333334
The lift for the rule is: 2.2196170583115755
***********************
The apriori rule is: fresh bread->chicken
The support for the rule is: 0.005199306759098787
The confidence for the rule is: 0.12074303405572756
The lift for the rule is: 2.0126522187822498
***********************
The apriori rule is: light cream->chicken
The support for the rule is: 0.004532728969470737
The confidence for the rule is: 0.29059829059829057
The lift for the rule is: 4.84395061728395
***********************
The apriori rule is: meatballs->chicken
The support for the rule is: 0.003199573390214638
The confidence for the rule is: 0.15286624203821658
The lift for the rule is: 2.548110403397028
***********************
The apriori rule is: tomato sauce->chocolate
The support for the rule is: 0.005065991201173177
The confidence for the rule is: 0.3584905660377358
The lift for the rule is: 2.1879883936932925
***********************
The apriori rule is: eggs->cider
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.4050632911392405
The lift for the rule is: 2.2539909101153137
***********************
The apriori rule is: milk->cider
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.31645569620253167
The lift for the rule is: 2.4421133510444344
***********************
The apriori rule is: grated cheese->cooking oil
The support for the rule is: 0.005732568990801226
The confidence for the rule is: 0.11227154046997388
The lift for the rule is: 2.1428723284103666
***********************
The apriori rule is: herb & pepper->cooking oil
The support for the rule is: 0.005332622317024397
The confidence for the rule is: 0.10443864229765012
The lift for the rule is: 2.111574813678365
***********************
The apriori rule is: cooking oil->soup
The support for the rule is: 0.005332622317024397
The confidence for the rule is: 0.10443864229765012
The lift for the rule is: 2.067003313653492
***********************
The apriori rule is: cottage cheese->frozen smoothie
The support for the rule is: 0.004932675643247567
The confidence for the rule is: 0.15481171548117154
The lift for the rule is: 2.4447214269984583
***********************
The apriori rule is: mushroom cream sauce->escalope
The support for the rule is: 0.005732568990801226
The confidence for the rule is: 0.3006993006993007
The lift for the rule is: 3.790832696715049
***********************
The apriori rule is: pasta->escalope
The support for the rule is: 0.005865884548726837
The confidence for the rule is: 0.3728813559322034
The lift for the rule is: 4.700811850163794
***********************
The apriori rule is: mineral water->extra dark chocolate
The support for the rule is: 0.005732568990801226
The confidence for the rule is: 0.47777777777777775
The lift for the rule is: 2.0043686303753416
***********************
The apriori rule is: green tea->flax seed
The support for the rule is: 0.0030662578322890282
The confidence for the rule is: 0.3382352941176471
The lift for the rule is: 2.560144239330445
***********************
The apriori rule is: olive oil->french wine
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.15384615384615383
The lift for the rule is: 2.336032388663967
***********************
The apriori rule is: tomato juice->fresh bread
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.14035087719298245
The lift for the rule is: 3.2593558198902826
***********************
The apriori rule is: honey->fresh tuna
The support for the rule is: 0.003999466737768298
The confidence for the rule is: 0.17964071856287428
The lift for the rule is: 3.7850703088205613
***********************
The apriori rule is: olive oil->fresh tuna
The support for the rule is: 0.0037328356219170776
The confidence for the rule is: 0.16766467065868262
The lift for the rule is: 2.5458556571068387
***********************
The apriori rule is: pancakes->fresh tuna
The support for the rule is: 0.005065991201173177
The confidence for the rule is: 0.2275449101796407
The lift for the rule is: 2.3938490480469636
***********************
The apriori rule is: honey->fromage blanc
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.2450980392156863
The lift for the rule is: 5.164270764485569
***********************
The apriori rule is: frozen smoothie->hot dogs
The support for the rule is: 0.004799360085321957
The confidence for the rule is: 0.14814814814814814
The lift for the rule is: 2.339493177387914
***********************
The apriori rule is: frozen smoothie->vegetables mix
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.1295336787564767
The lift for the rule is: 2.0455413144259618
***********************
The apriori rule is: parmesan cheese->frozen vegetables
The support for the rule is: 0.005465937874950006
The confidence for the rule is: 0.27516778523489926
The lift for the rule is: 2.886760219646125
***********************
The apriori rule is: shrimp->frozen vegetables
The support for the rule is: 0.01666444474070124
The confidence for the rule is: 0.17482517482517482
The lift for the rule is: 2.4465739484396196
***********************
The apriori rule is: frozen vegetables->tomatoes
The support for the rule is: 0.0161311825089988
The confidence for the rule is: 0.1692307692307692
The lift for the rule is: 2.4744639376218323
***********************
The apriori rule is: grated cheese->ground beef
The support for the rule is: 0.011331822423676844
The confidence for the rule is: 0.2162849872773537
The lift for the rule is: 2.201294015695292
***********************
The apriori rule is: grated cheese->herb & pepper
The support for the rule is: 0.006532462338354886
The confidence for the rule is: 0.12468193384223919
The lift for the rule is: 2.5208603389505018
***********************
The apriori rule is: grated cheese->salmon
The support for the rule is: 0.005199306759098787
The confidence for the rule is: 0.12225705329153606
The lift for the rule is: 2.333460958625476
***********************
The apriori rule is: green beans->spaghetti
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.39999999999999997
The lift for the rule is: 2.29739663093415
***********************
The apriori rule is: herb & pepper->ground beef
The support for the rule is: 0.015997866951073192
The confidence for the rule is: 0.1628222523744912
The lift for the rule is: 3.291993841134928
***********************
The apriori rule is: light cream->ground beef
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.2136752136752137
The lift for the rule is: 2.174732398612996
***********************
The apriori rule is: olive oil->ground beef
The support for the rule is: 0.014131449140114652
The confidence for the rule is: 0.14382632293080055
The lift for the rule is: 2.183889166607156
***********************
The apriori rule is: ground beef->pepper
The support for the rule is: 0.006532462338354886
The confidence for the rule is: 0.24623115577889446
The lift for the rule is: 2.5060785610549354
***********************
The apriori rule is: ground beef->rice
The support for the rule is: 0.004399413411545127
The confidence for the rule is: 0.23404255319148934
The lift for the rule is: 2.3820260400127022
***********************
The apriori rule is: ground beef->salmon
The support for the rule is: 0.008932142381015865
The confidence for the rule is: 0.21003134796238246
The lift for the rule is: 2.137646053006555
***********************
The apriori rule is: ground beef->spaghetti
The support for the rule is: 0.03919477403012932
The confidence for the rule is: 0.3989145183175034
The lift for the rule is: 2.291162176033379
***********************
The apriori rule is: tomato sauce->ground beef
The support for the rule is: 0.005332622317024397
The confidence for the rule is: 0.3773584905660377
The lift for the rule is: 3.840659481324083
***********************
The apriori rule is: olive oil->ham
The support for the rule is: 0.0035995200639914677
The confidence for the rule is: 0.13567839195979897
The lift for the rule is: 2.060169267389579
***********************
The apriori rule is: whole wheat rice->ham
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.1608040201005025
The lift for the rule is: 2.7475875962958294
***********************
The apriori rule is: herb & pepper->whole wheat pasta
The support for the rule is: 0.0037328356219170776
The confidence for the rule is: 0.12669683257918551
The lift for the rule is: 2.5615982241953383
***********************
The apriori rule is: olive oil->light cream
The support for the rule is: 0.003199573390214638
The confidence for the rule is: 0.20512820512820515
The lift for the rule is: 3.1147098515519573
***********************
The apriori rule is: light cream->pancakes
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.2222222222222222
The lift for the rule is: 2.3378525790868006
***********************
The apriori rule is: light mayo->pancakes
The support for the rule is: 0.005465937874950006
The confidence for the rule is: 0.20098039215686272
The lift for the rule is: 2.1143813766740918
***********************
The apriori rule is: meatballs->milk
The support for the rule is: 0.005465937874950006
The confidence for the rule is: 0.2611464968152866
The lift for the rule is: 2.0152879347854578
***********************
The apriori rule is: meatballs->tomatoes
The support for the rule is: 0.0038661511798426876
The confidence for the rule is: 0.18471337579617836
The lift for the rule is: 2.700848015296557
***********************
The apriori rule is: soup->milk
The support for the rule is: 0.015197973603519531
The confidence for the rule is: 0.11728395061728396
The lift for the rule is: 2.321231961953158
***********************
The apriori rule is: whole wheat pasta->milk
The support for the rule is: 0.009865351286495135
The confidence for the rule is: 0.33484162895927605
The lift for the rule is: 2.5839990317114503
***********************
The apriori rule is: mineral water->nonfat milk
The support for the rule is: 0.005065991201173177
The confidence for the rule is: 0.4871794871794871
The lift for the rule is: 2.0438105891126024
***********************
The apriori rule is: oil->shrimp
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.15028901734104047
The lift for the rule is: 2.103205072901389
***********************
The apriori rule is: olive oil->salmon
The support for the rule is: 0.005732568990801226
The confidence for the rule is: 0.1347962382445141
The lift for the rule is: 2.0467744596601216
***********************
The apriori rule is: olive oil->soup
The support for the rule is: 0.008932142381015865
The confidence for the rule is: 0.13562753036437247
The lift for the rule is: 2.684279961116512
***********************
The apriori rule is: olive oil->whole wheat pasta
The support for the rule is: 0.007998933475536596
The confidence for the rule is: 0.12145748987854252
The lift for the rule is: 4.1224100976422955
***********************
The apriori rule is: parmesan cheese->shrimp
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.16778523489932887
The lift for the rule is: 2.3480541921266154
***********************
The apriori rule is: parmesan cheese->tomatoes
The support for the rule is: 0.003199573390214638
The confidence for the rule is: 0.1610738255033557
The lift for the rule is: 2.3551944738804504
***********************
The apriori rule is: pasta->shrimp
The support for the rule is: 0.005065991201173177
The confidence for the rule is: 0.3220338983050847
The lift for the rule is: 4.506672147735896
***********************
The apriori rule is: pepper->spaghetti
The support for the rule is: 0.009865351286495135
The confidence for the rule is: 0.37185929648241206
The lift for the rule is: 2.1357707373005916
***********************
The apriori rule is: pepper->turkey
The support for the rule is: 0.0038661511798426876
The confidence for the rule is: 0.1457286432160804
The lift for the rule is: 2.3307261252959894
***********************
The apriori rule is: red wine->spaghetti
The support for the rule is: 0.010265297960271964
The confidence for the rule is: 0.36492890995260663
The lift for the rule is: 2.095966120638976
***********************
The apriori rule is: shrimp->tomatoes
The support for the rule is: 0.011198506865751233
The confidence for the rule is: 0.15671641791044774
The lift for the rule is: 2.2914811905385353
***********************
The apriori rule is: soup->tomatoes
The support for the rule is: 0.006932409012131715
The confidence for the rule is: 0.13720316622691292
The lift for the rule is: 2.0061616956492667
***********************
The apriori rule is: strong cheese->spaghetti
The support for the rule is: 0.0037328356219170776
The confidence for the rule is: 0.4827586206896552
The lift for the rule is: 2.7727200718170777
***********************
The apriori rule is: tomato sauce->spaghetti
The support for the rule is: 0.006265831222503666
The confidence for the rule is: 0.4433962264150943
The lift for the rule is: 2.546642491837383
***********************
The apriori rule is: almonds->nan
The support for the rule is: 0.005199306759098787
The confidence for the rule is: 0.25490196078431376
The lift for the rule is: 2.923577382023146
***********************
The apriori rule is: frozen smoothie->nan
The support for the rule is: 0.004932675643247567
The confidence for the rule is: 0.148
The lift for the rule is: 2.3420843881856537
***********************
The apriori rule is: mineral water->milk
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.1
The lift for the rule is: 2.0836111111111113
***********************
The apriori rule is: spaghetti->milk
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.1
The lift for the rule is: 2.819924812030075
***********************
The apriori rule is: soup->nan
The support for the rule is: 0.004399413411545127
The confidence for the rule is: 0.132
The lift for the rule is: 2.6124854881266493
***********************
The apriori rule is: bacon->nan
The support for the rule is: 0.003199573390214638
The confidence for the rule is: 0.36923076923076925
The lift for the rule is: 2.1206738131699847
***********************
The apriori rule is: black tea->nan
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.29906542056074764
The lift for the rule is: 2.3079112341833006
***********************
The apriori rule is: blueberries->nan
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.37681159420289856
The lift for the rule is: 2.164214217546663
***********************
The apriori rule is: body spray->french fries
The support for the rule is: 0.004266097853619517
The confidence for the rule is: 0.37209302325581395
The lift for the rule is: 2.17712150346479
***********************
The apriori rule is: cottage cheese->brownies
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.10276679841897232
The lift for the rule is: 3.2388813232802995
***********************
The apriori rule is: mineral water->brownies
The support for the rule is: 0.0035995200639914677
The confidence for the rule is: 0.10671936758893279
The lift for the rule is: 2.0955549117397507
***********************
The apriori rule is: chocolate->cake
The support for the rule is: 0.0030662578322890282
The confidence for the rule is: 0.17968750000000003
The lift for the rule is: 2.216835423519737
***********************
The apriori rule is: cake->burgers
The support for the rule is: 0.0034662045060658577
The confidence for the rule is: 0.18181818181818182
The lift for the rule is: 2.0853489018626634
***********************
The apriori rule is: cake->burgers
The support for the rule is: 0.0037328356219170776
The confidence for the rule is: 0.32558139534883723
The lift for the rule is: 2.5125370848885065
***********************
The apriori rule is: mineral water->cake
The support for the rule is: 0.004799360085321957
The confidence for the rule is: 0.19672131147540983
The lift for the rule is: 2.426984469370147
***********************
The apriori rule is: chocolate->burgers
The support for the rule is: 0.003332888948140248
The confidence for the rule is: 0.19531250000000003
The lift for the rule is: 2.049005681818182
***********************
The apriori rule is: chocolate->burgers
The support for the rule is: 0.005465937874950006
The confidence for the rule is: 0.3203125
The lift for the rule is: 2.4718766075102883
***********************
The apriori rule is: shrimp->chocolate
The support for the rule is: 0.0030662578322890282

## ECLAT Algorithm Implementation

In [10]:
import numpy as np
import pandas as pd 
from pyECLAT import ECLAT

data_frame = pd.read_csv("Datasets/data_market_basket.csv", header=None)

In [11]:
data_frame.head()

          0         1        2        3         4         5         6
0  corned_b   peppers  bourbon  cracker   chicken    apples      coke
1    olives   bourbon     coke   turkey  ice_crea       ham  baguette
2    hering  corned_b   olives      ham    turkey   bourbon   peppers
3  baguette  sardines   apples  peppers   avocado  ice_crea   bourbon
4  baguette      soda   hering  cracker  heineken   peppers    apples

In [12]:
eclat = ECLAT(data=data_frame)

In [13]:
get_eclat_indexes, get_ECLAT_supports = eclat.fit(
    min_support=0.02,
    min_combination=1,
    max_combination=3,
    separator=' & '
)

Combination 1 by 1

20it [00:00, 29.17it/s]

Combination 2 by 2

190it [00:03, 50.18it/s]

Combination 3 by 3

1140it [00:19, 59.99it/s]

In [14]:
get_ECLAT_supports

{'soda': 0.3176823176823177,
 'bordeaux': 0.07392607392607392,
 'chicken': 0.3146853146853147,
 'artichok': 0.3046953046953047,
 'apples': 0.31368631368631367,
 'ham': 0.3046953046953047,
 'turkey': 0.2827172827172827,
 'ice_crea': 0.3126873126873127,
 'corned_b': 0.3906093906093906,
 'sardines': 0.2957042957042957,
 'olives': 0.4725274725274725,
 'baguette': 0.3916083916083916,
 'hering': 0.4855144855144855,
 'cracker': 0.4875124875124875,
 'heineken': 0.5994005994005994,
 'coke': 0.2957042957042957,
 'peppers': 0.2957042957042957,
 'bourbon': 0.4025974025974026,
 'steak': 0.22677322677322678,
 'avocado': 0.3626373626373626,
 'soda & chicken': 0.06593406593406594,
 'soda & artichok': 0.061938061938061936,
 'soda & apples': 0.058941058941058944,
 'soda & ham': 0.054945054945054944,
 'soda & turkey': 0.05094905094905095,
 'soda & ice_crea': 0.055944055944055944,
 'soda & corned_b': 0.06993006993006994,
 'soda & sardines': 0.053946053946053944,
 'soda & olives': 0.16483516483516483,
 'soda & baguette': 0.15284715284715283,
 'soda & hering': 0.17382617382617382,
 'soda & cracker': 0.25074925074925075,
 'soda & heineken': 0.25674325674325676,
 'soda & coke': 0.05194805194805195,
 'soda & peppers': 0.06693306693306693,
 'soda & bourbon': 0.15484515484515485,
 'soda & steak': 0.05094905094905095,
 'soda & avocado': 0.07492507492507493,
 'bordeaux & artichok': 0.024975024975024976,
 'bordeaux & ham': 0.02097902097902098,
 'bordeaux & ice_crea': 0.023976023976023976,
 'bordeaux & corned_b': 0.023976023976023976,
 'bordeaux & olives': 0.03596403596403597,
 'bordeaux & baguette': 0.022977022977022976,
 'bordeaux & hering': 0.03196803196803197,
 'bordeaux & cracker': 0.03196803196803197,
 'bordeaux & heineken': 0.04395604395604396,
 'bordeaux & coke': 0.022977022977022976,
 'bordeaux & bourbon': 0.02097902097902098,
 'bordeaux & avocado': 0.028971028971028972,
 'chicken & artichok': 0.06893106893106893,
 'chicken & apples': 0.06693306693306693,
 'chicken & ham': 0.060939060939060936,
 'chicken & turkey': 0.04595404595404595,
 'chicken & ice_crea': 0.13986013986013987,
 'chicken & corned_b': 0.14285714285714285,
 'chicken & sardines': 0.13486513486513488,
 'chicken & olives': 0.07992007992007992,
 'chicken & baguette': 0.07792207792207792,
 'chicken & hering': 0.09290709290709291,
 'chicken & cracker': 0.16383616383616384,
 'chicken & heineken': 0.2007992007992008,
 'chicken & coke': 0.13886113886113885,
 'chicken & peppers': 0.12387612387612387,
 'chicken & bourbon': 0.14685314685314685,
 'chicken & steak': 0.04695304695304695,
 'chicken & avocado': 0.055944055944055944,
 'artichok & apples': 0.06393606393606394,
 'artichok & ham': 0.12787212787212787,
 'artichok & turkey': 0.054945054945054944,
 'artichok & ice_crea': 0.059940059940059943,
 'artichok & corned_b': 0.07492507492507493,
 'artichok & sardines': 0.054945054945054944,
 'artichok & olives': 0.07692307692307693,
 'artichok & baguette': 0.13486513486513488,
 'artichok & hering': 0.15684315684315683,
 'artichok & cracker': 0.15684315684315683,
 'artichok & heineken': 0.2517482517482518,
 'artichok & coke': 0.052947052947052944,
 'artichok & peppers': 0.04895104895104895,
 'artichok & bourbon': 0.07592407592407592,
 'artichok & steak': 0.04995004995004995,
 'artichok & avocado': 0.21078921078921078,
 'apples & ham': 0.052947052947052944,
 'apples & turkey': 0.057942057942057944,
 'apples & ice_crea': 0.06993006993006994,
 'apples & corned_b': 0.15084915084915085,
 'apples & sardines': 0.1258741258741259,
 'apples & olives': 0.15884115884115885,
 'apples & baguette': 0.14685314685314685,
 'apples & hering': 0.15684315684315683,
 'apples & cracker': 0.08791208791208792,
 'apples & heineken': 0.1048951048951049,
 'apples & coke': 0.07092907092907093,
 'apples & peppers': 0.12987012987012986,
 'apples & bourbon': 0.08491508491508491,
 'apples & steak': 0.11788211788211789,
 'apples & avocado': 0.13886113886113885,
 'ham & turkey': 0.13386613386613386,
 'ham & ice_crea': 0.07092907092907093,
 'ham & corned_b': 0.15984015984015984,
 'ham & sardines': 0.05194805194805195,
 'ham & olives': 0.15784215784215785,
 'ham & baguette': 0.055944055944055944,
 'ham & hering': 0.15984015984015984,
 'ham & cracker': 0.14985014985014986,
 'ham & heineken': 0.17382617382617382,
 'ham & coke': 0.06293706293706294,
 'ham & peppers': 0.052947052947052944,
 'ham & bourbon': 0.07792207792207792,
 'ham & steak': 0.05194805194805195,
 'ham & avocado': 0.13786213786213786,
 'turkey & ice_crea': 0.1258741258741259,
 'turkey & corned_b': 0.13386613386613386,
 'turkey & sardines': 0.04995004995004995,
 'turkey & olives': 0.22077922077922077,
 'turkey & baguette': 0.06893106893106893,
 'turkey & hering': 0.14985014985014986,
 'turkey & cracker': 0.07292707292707293,
 'turkey & heineken': 0.0919080919080919,
 'turkey & coke': 0.11888111888111888,
 'turkey & peppers': 0.04795204795204795,
 'turkey & bourbon': 0.13986013986013987,
 'turkey & steak': 0.04795204795204795,
 'turkey & avocado': 0.055944055944055944,
 'ice_crea & corned_b': 0.06593406593406594,
 'ice_crea & sardines': 0.15084915084915085,
 'ice_crea & olives': 0.15484515484515485,
 'ice_crea & baguette': 0.07292707292707293,
 'ice_crea & hering': 0.07292707292707293,
 'ice_crea & cracker': 0.08491508491508491,
 'ice_crea & heineken': 0.1838161838161838,
 'ice_crea & coke': 0.21978021978021978,
 'ice_crea & peppers': 0.061938061938061936,
 'ice_crea & bourbon': 0.14485514485514486,
 'ice_crea & steak': 0.04695304695304695,
 'ice_crea & avocado': 0.053946053946053944,
 'corned_b & sardines': 0.06593406593406594,
 'corned_b & olives': 0.23676323676323677,
 'corned_b & baguette': 0.09090909090909091,
 'corned_b & hering': 0.24475524475524477,
 'corned_b & cracker': 0.16983016983016982,
 'corned_b & heineken': 0.1258741258741259,
 'corned_b & coke': 0.061938061938061936,
 'corned_b & peppers': 0.13786213786213786,
 'corned_b & bourbon': 0.15284715284715283,
 'corned_b & steak': 0.13286713286713286,
 'corned_b & avocado': 0.08291708291708291,
 'sardines & olives': 0.07492507492507493,
 'sardines & baguette': 0.13186813186813187,
 'sardines & hering': 0.07292707292707293,
 'sardines & cracker': 0.07992007992007992,
 'sardines & heineken': 0.18181818181818182,
 'sardines & coke': 0.14685314685314685,
 'sardines & peppers': 0.11988011988011989,
 'sardines & bourbon': 0.07292707292707293,
 'sardines & steak': 0.04395604395604396,
 'sardines & avocado': 0.12687312687312688,
 'olives & baguette': 0.0999000999000999,
 'olives & hering': 0.25574425574425574,
 'olives & cracker': 0.1848151848151848,
 'olives & heineken': 0.20279720279720279,
 'olives & coke': 0.14785214785214784,
 'olives & peppers': 0.08291708291708291,
 'olives & bourbon': 0.24475524475524477,
 'olives & steak': 0.14585414585414586,
 'olives & avocado': 0.08291708291708291,
 'baguette & hering': 0.24875124875124874,
 'baguette & cracker': 0.17682317682317683,
 'baguette & heineken': 0.26073926073926074,
 'baguette & coke': 0.06593406593406594,
 'baguette & peppers': 0.13886113886113885,
 'baguette & bourbon': 0.0939060939060939,
 'baguette & steak': 0.06593406593406594,
 'baguette & avocado': 0.21478521478521478,
 'hering & cracker': 0.2007992007992008,
 'hering & heineken': 0.28771228771228774,
 'hering & coke': 0.06793206793206794,
 'hering & peppers': 0.07992007992007992,
 'hering & bourbon': 0.10789210789210789,
 'hering & steak': 0.14885114885114886,
 'hering & avocado': 0.16983016983016982,
 'cracker & heineken': 0.36563436563436563,
 'cracker & coke': 0.07492507492507493,
 'cracker & peppers': 0.16083916083916083,
 'cracker & bourbon': 0.23976023976023977,
 'cracker & steak': 0.07992007992007992,
 'cracker & avocado': 0.16283716283716285,
 'heineken & coke': 0.17382617382617382,
 'heineken & peppers': 0.1038961038961039,
 'heineken & bourbon': 0.2097902097902098,
 'heineken & steak': 0.08791208791208792,
 'heineken & avocado': 0.24875124875124874,
 'coke & peppers': 0.054945054945054944,
 'coke & bourbon': 0.13986013986013987,
 'coke & steak': 0.04195804195804196,
 'coke & avocado': 0.04595404595404595,
 'peppers & bourbon': 0.15384615384615385,
 'peppers & steak': 0.04695304695304695,
 'peppers & avocado': 0.1258741258741259,
 'bourbon & steak': 0.060939060939060936,
 'bourbon & avocado': 0.06693306693306693,
 'steak & avocado': 0.06393606393606394,
 'soda & chicken & olives': 0.023976023976023976,
 'soda & chicken & baguette': 0.023976023976023976,
 'soda & chicken & hering': 0.023976023976023976,
 'soda & chicken & cracker': 0.052947052947052944,
 'soda & chicken & heineken': 0.04895104895104895,
 'soda & chicken & peppers': 0.02097902097902098,
 'soda & chicken & bourbon': 0.03496503496503497,
 'soda & artichok & baguette': 0.029970029970029972,
 'soda & artichok & hering': 0.030969030969030968,
 'soda & artichok & cracker': 0.04795204795204795,
 'soda & artichok & heineken': 0.058941058941058944,
 'soda & artichok & avocado': 0.029970029970029972,
 'soda & apples & olives': 0.03196803196803197,
 'soda & apples & baguette': 0.028971028971028972,
 'soda & apples & hering': 0.027972027972027972,
 'soda & apples & cracker': 0.030969030969030968,
 'soda & apples & heineken': 0.03396603396603397,
 'soda & ham & olives': 0.024975024975024976,
 'soda & ham & hering': 0.026973026973026972,
 'soda & ham & cracker': 0.03896103896103896,
 'soda & ham & heineken': 0.03896103896103896,
 'soda & turkey & olives': 0.03896103896103896,
 'soda & turkey & hering': 0.027972027972027972,
 'soda & turkey & cracker': 0.024975024975024976,
 'soda & turkey & heineken': 0.024975024975024976,
 'soda & turkey & bourbon': 0.028971028971028972,
 'soda & ice_crea & olives': 0.027972027972027972,
 'soda & ice_crea & cracker': 0.026973026973026972,
 'soda & ice_crea & heineken': 0.03796203796203796,
 'soda & ice_crea & coke': 0.026973026973026972,
 'soda & ice_crea & bourbon': 0.027972027972027972,
 'soda & corned_b & olives': 0.04195804195804196,
 'soda & corned_b & baguette': 0.02097902097902098,
 'soda & corned_b & hering': 0.04295704295704296,
 'soda & corned_b & cracker': 0.04695304695304695,
 'soda & corned_b & heineken': 0.030969030969030968,
 'soda & corned_b & bourbon': 0.03496503496503497,
 'soda & sardines & baguette': 0.029970029970029972,
 'soda & sardines & cracker': 0.026973026973026972,
 'soda & sardines & heineken': 0.03596403596403597,
 'soda & olives & baguette': 0.03596403596403597,
 'soda & olives & hering': 0.06493506493506493,
 'soda & olives & cracker': 0.1258741258741259,
 'soda & olives & heineken': 0.12687312687312688,
 'soda & olives & coke': 0.028971028971028972,
 'soda & olives & peppers': 0.023976023976023976,
 'soda & olives & bourbon': 0.12387612387612387,
 'soda & olives & steak': 0.029970029970029972,
 'soda & baguette & hering': 0.12887112887112886,
 'soda & baguette & cracker': 0.12687312687312688,
 'soda & baguette & heineken': 0.13786213786213786,
 'soda & baguette & peppers': 0.03396603396603397,
 'soda & baguette & bourbon': 0.027972027972027972,
 'soda & baguette & avocado': 0.04495504495504495,
 'soda & hering & cracker': 0.14085914085914086,
 'soda & hering & heineken': 0.14885114885114886,
 'soda & hering & peppers': 0.022977022977022976,
 'soda & hering & bourbon': 0.04095904095904096,
 'soda & hering & steak': 0.03296703296703297,
 'soda & hering & avocado': 0.03796203796203796,
 'soda & cracker & heineken': 0.23376623376623376,
 'soda & cracker & coke': 0.024975024975024976,
 'soda & cracker & peppers': 0.052947052947052944,
 'soda & cracker & bourbon': 0.13586413586413587,
 'soda & cracker & steak': 0.03896103896103896,
 'soda & cracker & avocado': 0.04695304695304695,
 'soda & heineken & coke': 0.03496503496503497,
 'soda & heineken & peppers': 0.03796203796203796,
 'soda & heineken & bourbon': 0.12387612387612387,
 'soda & heineken & steak': 0.03796203796203796,
 'soda & heineken & avocado': 0.057942057942057944,
 'soda & coke & bourbon': 0.026973026973026972,
 'soda & peppers & bourbon': 0.03896103896103896,
 'bordeaux & artichok & heineken': 0.02197802197802198,
 'bordeaux & artichok & avocado': 0.02097902097902098,
 'bordeaux & cracker & heineken': 0.024975024975024976,
 'bordeaux & heineken & avocado': 0.022977022977022976,
 'chicken & artichok & corned_b': 0.02197802197802198,
 'chicken & artichok & baguette': 0.024975024975024976,
 'chicken & artichok & hering': 0.026973026973026972,
 'chicken & artichok & cracker': 0.029970029970029972,
 'chicken & artichok & heineken': 0.054945054945054944,
 'chicken & artichok & coke': 0.02097902097902098,
 'chicken & artichok & avocado': 0.03196803196803197,
 'chicken & apples & corned_b': 0.03796203796203796,
 'chicken & apples & sardines': 0.026973026973026972,
 'chicken & apples & hering': 0.02197802197802198,
 'chicken & apples & cracker': 0.028971028971028972,
 'chicken & apples & heineken': 0.028971028971028972,
 'chicken & apples & coke': 0.02197802197802198,
 'chicken & apples & peppers': 0.027972027972027972,
 'chicken & apples & bourbon': 0.024975024975024976,
 'chicken & ham & ice_crea': 0.02097902097902098,
 'chicken & ham & corned_b': 0.03196803196803197,
 'chicken & ham & sardines': 0.02197802197802198,
 'chicken & ham & cracker': 0.030969030969030968,
 'chicken & ham & heineken': 0.03796203796203796,
 'chicken & ham & coke': 0.02197802197802198,
 'chicken & turkey & corned_b': 0.02197802197802198,
 'chicken & turkey & olives': 0.02097902097902098,
 'chicken & turkey & coke': 0.02097902097902098,
 'chicken & turkey & bourbon': 0.02097902097902098,
 'chicken & ice_crea & corned_b': 0.030969030969030968,
 'chicken & ice_crea & sardines': 0.11588411588411589,
 'chicken & ice_crea & olives': 0.027972027972027972,
 'chicken & ice_crea & cracker': 0.03296703296703297,
 'chicken & ice_crea & heineken': 0.11888111888111888,
 'chicken & ice_crea & coke': 0.12287712287712288,
 'chicken & ice_crea & peppers': 0.028971028971028972,
 'chicken & ice_crea & bourbon': 0.04195804195804196,
 'chicken & corned_b & sardines': 0.027972027972027972,
 'chicken & corned_b & olives': 0.03796203796203796,
 'chicken & corned_b & hering': 0.04295704295704296,
 'chicken & corned_b & cracker': 0.1008991008991009,
 'chicken & corned_b & heineken': 0.04295704295704296,
 'chicken & corned_b & coke': 0.029970029970029972,
 'chicken & corned_b & peppers': 0.0959040959040959,
 'chicken & corned_b & bourbon': 0.0979020979020979,
 'chicken & corned_b & steak': 0.030969030969030968,
 'chicken & sardines & olives': 0.02197802197802198,
 'chicken & sardines & baguette': 0.023976023976023976,
 'chicken & sardines & cracker': 0.023976023976023976,
 'chicken & sardines & heineken': 0.11888111888111888,
 'chicken & sardines & coke': 0.11688311688311688,
 'chicken & sardines & peppers': 0.029970029970029972,
 'chicken & sardines & bourbon': 0.030969030969030968,
 'chicken & olives & hering': 0.030969030969030968,
 'chicken & olives & cracker': 0.03496503496503497,
 'chicken & olives & heineken': 0.03896103896103896,
 'chicken & olives & coke': 0.027972027972027972,
 'chicken & olives & bourbon': 0.03896103896103896,
 'chicken & baguette & hering': 0.03896103896103896,
 'chicken & baguette & cracker': 0.03896103896103896,
 'chicken & baguette & heineken': 0.054945054945054944,
 'chicken & baguette & peppers': 0.026973026973026972,
 'chicken & baguette & bourbon': 0.022977022977022976,
 'chicken & baguette & avocado': 0.027972027972027972,
 'chicken & hering & cracker': 0.03996003996003996,
 'chicken & hering & heineken': 0.052947052947052944,
 'chicken & hering & coke': 0.02197802197802198,
 'chicken & hering & peppers': 0.02097902097902098,
 'chicken & hering & bourbon': 0.023976023976023976,
 'chicken & hering & avocado': 0.02197802197802198,
 'chicken & cracker & heineken': 0.08591408591408592,
 'chicken & cracker & coke': 0.028971028971028972,
 'chicken & cracker & peppers': 0.0989010989010989,
 'chicken & cracker & bourbon': 0.11288711288711288,
 'chicken & cracker & steak': 0.02197802197802198,
 'chicken & cracker & avocado': 0.023976023976023976,
 'chicken & heineken & coke': 0.11788211788211789,
 'chicken & heineken & peppers': 0.03896103896103896,
 'chicken & heineken & bourbon': 0.061938061938061936,
 'chicken & heineken & avocado': 0.04395604395604396,
 'chicken & coke & peppers': 0.027972027972027972,
 'chicken & coke & bourbon': 0.03996003996003996,
 'chicken & peppers & bourbon': 0.1008991008991009,
 'artichok & apples & olives': 0.02097902097902098,
 'artichok & apples & baguette': 0.03296703296703297,
 'artichok & apples & hering': 0.03796203796203796,
 'artichok & apples & heineken': 0.03896103896103896,
 'artichok & apples & avocado': 0.04295704295704296,
 'artichok & ham & turkey': 0.026973026973026972,
 'artichok & ham & ice_crea': 0.025974025974025976,
 'artichok & ham & corned_b': 0.030969030969030968,
 'artichok & ham & olives': 0.027972027972027972,
 'artichok & ham & hering': 0.03696303696303696,
 'artichok & ham & cracker': 0.1008991008991009,
 'artichok & ham & heineken': 0.11288711288711288,
 'artichok & ham & bourbon': 0.02197802197802198,
 'artichok & ham & avocado': 0.11288711288711288,
 'artichok & turkey & olives': 0.025974025974025976,
 'artichok & turkey & hering': 0.03196803196803197,
 'artichok & turkey & heineken': 0.03296703296703297,
 'artichok & turkey & avocado': 0.025974025974025976,
 'artichok & ice_crea & sardines': 0.02197802197802198,
 'artichok & ice_crea & heineken': 0.04495504495504495,
 'artichok & ice_crea & coke': 0.03496503496503497,
 'artichok & ice_crea & avocado': 0.024975024975024976,
 'artichok & corned_b & olives': 0.029970029970029972,
 'artichok & corned_b & baguette': 0.022977022977022976,
 'artichok & corned_b & hering': 0.04395604395604396,
 'artichok & corned_b & cracker': 0.03596403596403597,
 'artichok & corned_b & heineken': 0.04195804195804196,
 'artichok & corned_b & avocado': 0.03896103896103896,
 'artichok & sardines & baguette': 0.024975024975024976,
 'artichok & sardines & heineken': 0.04595404595404595,
 'artichok & sardines & avocado': 0.03196803196803197,
 'artichok & olives & hering': 0.03896103896103896,
 'artichok & olives & cracker': 0.03196803196803197,
 'artichok & olives & heineken': 0.03896103896103896,
 'artichok & olives & bourbon': 0.03196803196803197,
 'artichok & olives & avocado': 0.026973026973026972,
 'artichok & baguette & hering': 0.11588411588411589,
 'artichok & baguette & cracker': 0.03396603396603397,
 'artichok & baguette & heineken': 0.12287712287712288,
 'artichok & baguette & peppers': 0.02097902097902098,
 'artichok & baguette & avocado': 0.11188811188811189,
 'artichok & hering & cracker': 0.04595404595404595,
 'artichok & hering & heineken': 0.12987012987012986,
 'artichok & hering & bourbon': 0.02197802197802198,
 'artichok & hering & steak': 0.030969030969030968,
 'artichok & hering & avocado': 0.11688311688311688,
 'artichok & cracker & heineken': 0.14385614385614387,
 'artichok & cracker & peppers': 0.029970029970029972,
 'artichok & cracker & bourbon': 0.04095904095904096,
 'artichok & cracker & avocado': 0.11288711288711288,
 'artichok & heineken & coke': 0.03896103896103896,
 'artichok & heineken & peppers': 0.030969030969030968,
 'artichok & heineken & bourbon': 0.05194805194805195,
 'artichok & heineken & steak': 0.03396603396603397,
 'artichok & heineken & avocado': 0.19880119880119881,
 'artichok & peppers & avocado': 0.03196803196803197,
 'artichok & bourbon & avocado': 0.030969030969030968,
 'artichok & steak & avocado': 0.029970029970029972,
 'apples & ham & corned_b': 0.030969030969030968,
 'apples & ham & olives': 0.03196803196803197,
 'apples & ham & hering': 0.03696303696303696,
 'apples & ham & heineken': 0.02097902097902098,
 'apples & ham & avocado': 0.02097902097902098,
 'apples & turkey & ice_crea': 0.022977022977022976,
 'apples & turkey & corned_b': 0.029970029970029972,
 'apples & turkey & olives': 0.04295704295704296,
 'apples & turkey & hering': 0.026973026973026972,

## F-P Algorithm

In [2]:
from mlxtend.frequent_patterns import fpgrowth
from mlxtend.preprocessing import TransactionEncoder
import pandas as pd

In [3]:
# Create example dataset

dataset = [['milk','bread','butter'], ['milk', 'bread'], ['milk','butter'],
           ['bread', 'butter'], ['milk','bread', 'butter', 'eggs'], ['eggs', 'butter']]

In [5]:
# Create transactional encoder and transform data
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

In [6]:
# Generate frequent itemsets
frequent_itemsets = fpgrowth(df, min_support=0.05, use_colnames=True)

# Sort frequent itemsets by support
frequent_itemsets=frequent_itemsets.sort_values(by='support', ascending=False)

#Print top 10 frequent itemsets
print(frequent_itemsets.head(10))

    support                          itemsets
0  0.833333               frozenset({butter})
1  0.666667                 frozenset({milk})
2  0.666667                frozenset({bread})
4  0.500000         frozenset({butter, milk})
5  0.500000          frozenset({bread, milk})
6  0.500000        frozenset({bread, butter})
3  0.333333                 frozenset({eggs})
7  0.333333  frozenset({bread, butter, milk})
8  0.333333         frozenset({eggs, butter})
9  0.166667          frozenset({bread, eggs})